# Generated by Django 5.1.6 on 2025-02-11 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_ticketlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketlog',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ticket.ticket'),
        ),
    ]
