# Generated by Django 5.1.6 on 2025-02-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticketlog_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
